### ISSUE TITLE
Add CreationTemplate.ini and SettingsTemplate.ini to template

### ISSUE THREAD

**Issue by sausagejohnson** [orx/orx#27]
Add CreationTemplate.ini and SettingsTemplate.ini to template/data/config

and include in the solution alongside the other three *.ini

This way the creation and settings files are available in each created project for the user's convenience.

**Comment by iarwain** [comment]
Sure why not, though I'll probably add a switch to deactivate it even if deleting them is a very minor chore.
I just know that personally I'd rather not have them around my projects and maybe it might be the same for others.

**Comment by sausagejohnson** [comment]
Just to add to that, I personally survive on those lists, so unless you know everything off by heart, it's super handy to be available.

**Comment by iarwain** [comment]
I use the completion file for Sublime Text. :)
