### ISSUE TITLE
[Feature request] What about Vulkan?

### ISSUE THREAD

**Issue by trsh** [orx/orx#29]
https://www.anandtech.com/show/12465/khronos-group-extends-vulkan-portability-with-opensource

**Comment by iarwain** [comment]
We'll probably switch to Vulkan when we rewrite the rendering/display, especially now that someone added support for OSX/iOS. It's been on our radar since its announcement.

**Comment by trsh** [comment]
Cool! Btw you can mark github issues labels, like 'Feature request', 'Bug', etc. To keep better track.

**Comment by iarwain** [comment]
Ah sure, I do use the bitbucket issue to track the bugs/small feature request though. The github account is the mirror one. We also have Trello for tracking the bigger features to come.

**Comment by trsh** [comment]
@iarwain OK. Then if you wish, u can close this ;). My question is answered.
