### ISSUE TITLE
MyOrxGame make fails mac mojave

### ISSUE THREAD

**Issue by songproducer** [orx/orx#36]
> ==== Building MyOrxGame (debug64) ====
> Linking MyOrxGame
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> ld: warning: directory not found for option '-L/usr/lib64'
> ld: library not found for -lstdc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [../../../bin/MyOrxGamed] Error 1
> make: *** [MyOrxGame] Error 2
>

**Comment by songproducer** [comment]
Not sure if this is the reason why but I installed orx in my home directory rather than Documents.

**Comment by iarwain** [comment]
Hi @songproducer ,

Looks like libstdc++ has been completely removed from recent versions of OSX.
[We actually discussed that on the chat last December](https://gitter.im/orx/orx?at=5c16ae77e86b0460b3aa7795), unfortunately we didn't get a chance to find a final solution.

The main issue being that Apple won't let me update to Mojave as they locked my macbook to OSX 10.11, and I'm not able to test it first hand. It should be an easy fix in the premake files though, so if you're willing to do a bit of back and forth with, we should be able to fix it shortly.

**Comment by songproducer** [comment]
Hi @iarwain I'd be happy to try and help get a fix just let me know what to do.

**Comment by iarwain** [comment]
I've made a fix attempt in a [patch](https://github.com/orx/orx/files/2871745/libc%2B%2B.zip). If you could:
- unzip the patch
- apply it on the latest version of the repository
- re-run setup.sh/init.sh
- let me know if it's working for you, 
that'd be great.

**Comment by songproducer** [comment]
I'm not sure if I applied the patch properly. I just unzipped it in the orx directory. Ran setup and init but got the same error.

**Comment by iarwain** [comment]
When you unzip it, you should get a file with a `.patch` extension. You should then apply it on your repository using the [`git apply`](https://git-scm.com/docs/git-apply) command.

**Comment by iarwain** [comment]
If this turns out to be too troublesome, I should be able to send you a zip that contains all the files.

**Comment by songproducer** [comment]
Aha thanks!

I get a different error now:

> ==== Building MyOrxGame (debug64) ====
> MyOrxGame.cpp
> warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead
>       [-Wstdlibcxx-not-found]
> ../../../src/MyOrxGame.cpp:34:10: fatal error: 'orx.h' file not found
> #include "orx.h"
>          ^~~~~~~
> 1 warning and 1 error generated.
> make[1]: *** [obj/x64/Debug/MyOrxGame.o] Error 1
> make: *** [MyOrxGame] Error 2
>

**Comment by iarwain** [comment]
Actually, do you mind joining the chat on https://gitter.im/orx/orx (it uses your github credentials, no need for a new account)? That might be more efficient. :)

**Comment by songproducer** [comment]
> ==== Building MyOrxGame (debug64) ====
> Creating obj/x64/Debug
> MyOrxGame.cpp
> warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
> 1 warning generated.
> Linking MyOrxGame
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> ld: warning: directory not found for option '-L/usr/lib64'
> ld: library not found for -lstdc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [../../../bin/MyOrxGamed] Error 1
> make: *** [MyOrxGame] Error 2
>

**Comment by iarwain** [comment]
Thanks to your help debugging it, it should be fixed in https://github.com/orx/orx/commit/4bc12ecf5dfcdd280e7ff6be5c8e04b781f15cf3
