### ISSUE TITLE
will there be a golang binding for this engine?

### ISSUE THREAD

**Issue by fastfading** [orx/orx#39]
golang is easy bind to c through cgo.
and golang is easy to use, programer would not have to worry about the crash and other c problems.
strongly to sugguest to bind golang
one simple solution is to build golang language as .so or .a file, link them in game.

**Comment by iarwain** [comment]
Hi,

We do not have any plans to add Go bindings ourselves. However if you want to contribute with such bindings, you're more than welcome to do so.
