### ISSUE TITLE
Improve install process

### ISSUE THREAD

**Issue by Howld** [orx/orx#42]
I download this "orx-src-1.10.zip" file from Github, and run init script on CMD with error message about couldn't find "premake4.exe" file. Although I copy it from "tools" directory, please fix this small fault.

<pre>
D:\NormalPrograms\orx-1.10>init
== No argument, switching to interactive mode
 * Project name (relative or full path)? Game
[ 20:46:50 ] New orx installation found, running setup!
== Checking version: [ extern/ ]
== [ b1cb325302a5 ] needed, current [ ]
== [ b1cb325302a5 ] not in cache
== Fetching [ http://orx-project.org/extern/b1cb325302a5.zip ]
== Please wait!
** Access Error: protocol error: "Server error: HTTP/1.0 404 Not Found"
** Where: fail switch awake switch check-response switch --anonymous-- wake-up either until --anonymous-- wait until sync-op either --anonymous-- read either either do catch either either --anonymous-- do trap if --anonymous--
** Near: _ fail error ??
** File: code/build/rebol/setup.r
** Line: 51
[ 20:46:51 ] Initializing [ Game ] in [ D:\NormalPrograms\orx-1.10\ ]
[ 20:46:51 ] == Creating files:
  + Game\.editorconfig
  + Game\build\premake4.lua
  + Game\data\config\CreationTemplate.ini
  + Game\data\config\SettingsTemplate.ini
  + Game\data\config\Game.ini
  + Game\data\config\Gamed.ini
  + Game\data\config\Gamep.ini
  + Game\data\sound\appear.ogg
  + Game\data\texture\logo.png
  + Game\src\Game.cpp
** Access Error: cannot open: %/D/NormalPrograms/orx-1.10/code/build/template/../premake4.exe reason: -3
** Where: read do in-dir if do catch either either --anonymous-- do trap if --anonymous--
** Near: platform-info/premake read source/:premake-source ?? unless ...
** File: /D/NormalPrograms/orx-1.10/code/build/rebol/init.r
** Line: 49
</pre>

**Comment by iarwain** [comment]
Hi @Howld,

The 1.10 release is over 8 months old and unfortunately the URL used to fetch the dependencies doesn't exist anymore. I'll put that version of the dependencies back to that URL tonight.

In the meantime, I'd recommend cloning the source repository instead: everything should work smoothly with an up-to-date setup URL and you'll get all the features that have been added since 1.10 as well.

**Comment by iarwain** [comment]
As a side note, per the installation note found on [the wiki](https://orx-project.org/wiki/en/tutorials/cloning_orx_from_github), you should be running `setup` instead. `init` is used to start a new project (though it'll call `setup` behind the scene if need be).

**Comment by Howld** [comment]
Can you put source on "https://orx-project.org/", because I can't use git tool with single digit KB speed. I'm tired to find a way to download source on Github.

**Comment by iarwain** [comment]
Would you get better results with https://bitbucket.org/orx/orx/get/c5ffdbc592d5.zip by any chance?

**Comment by Howld** [comment]
No better, same worse, download failed.

**Comment by iarwain** [comment]
I've updated the external dependencies, you should be able to run setup with the 1.10 source archive you've already downloaded.

**Comment by Howld** [comment]
I use VS2017 and it said "Can't open input file orxd.lib". By the way, I have to sleep, thanks a lot.

**Comment by iarwain** [comment]
Would you mind continuing this conversation on https://gitter.im/orx/orx or https://forum.orx-project.org ? It'd be easier there for other members of the community to help you as well. :)

So I `setup` went fine? Did you build orx afterward? The solution for VS2017 will be in `/code/build/windows/vs2017`

Have a good night!

**Comment by Yzubi** [comment]
> No better, same worse, download failed.

Have you tried downloading the latest orx source using wget/curl? (Or other download management tool?) i always use these when my connection gets unstable.

**For wget**

Github repo:
```
wget https://github.com/orx/orx/archive/master.zip
```
Bitbucket repo:
```
wget https://bitbucket.org/orx/orx/get/default.zip
```

**For curl**

Github repo:
```
curl https://codeload.github.com/orx/orx/zip/master --output orx.zip
```

Bitbucket repo:
```
curl https://bitbucket.org/orx/orx/get/default.zip --output orx.zip
```

On Linux, these utilities are probably already installed, if not, you can easily install them using a package manager. For Windows, see these links:

wget: https://eternallybored.org/misc/wget/
curl: https://curl.haxx.se/windows/

**Comment by Howld** [comment]
I download the source from Github, and compiled it, it's work. Thank your patient! @iarwain

**Comment by iarwain** [comment]
Glad you got it working. Don't hesitate if you have any questions!
