### ISSUE TITLE
orxObject_Raycast crashes when begin == end

### ISSUE THREAD

**Issue by znakeeye** [orx/orx#46]
Simply run this:

```c
orxSTATUS orxFASTCALL Init()
{
    auto begin = orxVECTOR_1;
    auto end = orxVECTOR_1;
    orxObject_Raycast(&begin, &end, 0, 0, orxTRUE, orxNULL, orxNULL);
    // ...
}
```

That code will crash:

> Assertion failed!
> 
> Program: \bin\orxd.dll
> File: C:\workspace\liquidfun\liquidfun\Box2.../b2DynamicTree.h
> Line: 209
> 
> Expression: r.LengthSquared() > 0.0f
>

**Comment by iarwain** [comment]
That's not a crash, this is an assert in debug letting you know that you cannot use a ray of length == 0 for a raycast. Also it's a Box2D assert, which is unrelated to orx.
For more info about raycasts in Box2D, you can consult http://www.iforce2d.net/b2dtut/raycasting

**Comment by znakeeye** [comment]
Ok, so manual check is needed before calling the method then.
