### ISSUE TITLE
Clang - illegal core dump - GCC slow FPS on Linux Intel Integrated graphic card

### ISSUE THREAD

**Issue by OneArb** [orx/orx#47]
On GCC, the following code produces an FPS that slows down over a few minutes down to 1 and hangs.

On Clang it does not render anything and produces an "illegal core dump" message.

```
/**
 * @file draw.cpp
 * @date 11-Dec-2019
 */

#include "orx.h"

/*
 * This is a basic code template to quickly and easily get started with a project or tutorial.
 */

orxSTATUS orxFASTCALL RenderEventHandler(const orxEVENT *_pstEvent) {
	if (_pstEvent->eType == orxEVENT_TYPE_RENDER){
		if(_pstEvent->eID == orxRENDER_EVENT_STOP){

static orxFLOAT rotate_angle;
orxOBOX boxArea;

      orxVECTOR topLeft = { 400, 400, 0 };
      orxVECTOR size = { 200, 200, 0 };
      orxVECTOR pivot = { 0, 0, 0 };

      orxOBox_2DSet(&boxArea, &topLeft, &pivot, &size, 0);

      rotate_angle--;
      orxOBox_2DRotate(&boxArea, &boxArea ,rotate_angle);

      orxRGBA colour;
      colour.u8R = 0;
      colour.u8G = 125;
      colour.u8B = 180;
      colour.u8A = 200;

      orxDisplay_DrawOBox( &boxArea, colour, orxFALSE);

		}
	}

	return orxSTATUS_SUCCESS;
}

/** Init function, it is called when all orx's modules have been initialized
 */
orxSTATUS orxFASTCALL Init()
{
    // Display a small hint in console
    orxLOG("\n* This template project creates a viewport/camera couple and an object"
    "\n* You can play with the config parameters in ../data/config/draw.ini"
    "\n* After changing them, relaunch the executable to see the changes.");

    // Create the viewport
    orxViewport_CreateFromConfig("Viewport");

    // Create the object
    // orxObject_CreateFromConfig("Object");

    // Done!
    return orxSTATUS_SUCCESS;
}

/** Run function, it is called every clock cycle
 */
orxSTATUS orxFASTCALL Run()
{
  orxSTATUS eResult = orxSTATUS_SUCCESS;

  orxEvent_AddHandler(orxEVENT_TYPE_RENDER, RenderEventHandler);

  // Should quit?
  if(orxInput_IsActive("Quit"))
  {
      // Update result
      eResult = orxSTATUS_FAILURE;
  }
  // Done!
  return eResult;
}

/** Exit function, it is called before exiting from orx
 */
void orxFASTCALL Exit()
{
    // Let Orx clean all our mess automatically. :)
}

/** Bootstrap function, it is called before config is initialized, allowing for early resource storage definitions
 */
orxSTATUS orxFASTCALL Bootstrap()
{
    // Add a config storage to find the initial config file
    orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, "../data/config", orxFALSE);

    // Return orxSTATUS_FAILURE to prevent orx from loading the default config file
    return orxSTATUS_SUCCESS;
}

/** Main function
 */
int main(int argc, char **argv)
{
    // Set the bootstrap function to provide at least one resource storage before loading any config files
    orxConfig_SetBootstrap(Bootstrap);

    // Execute our game
    orx_Execute(argc, argv, Init, Run, Exit);

    // Done!
    return EXIT_SUCCESS;
}
```

ini file
```
; draw - Template basic config file

[Display]
Title           = draw
FullScreen      = true
Decoration      = false
Smoothing       = false
VSync           = true

[Resource]
Texture         = ../data/texture
Sound           = ../data/sound

[Input]
SetList         = MainInput

[MainInput]
KEY_ESCAPE      = Quit

[Viewport]
Camera          = Camera

[Camera]
FrustumWidth    = 1280
FrustumHeight   = 720
FrustumFar      = 2
FrustumNear     = 0
Position        = (0, 0, -1) ; Objects with -1 <= Z <= 1 will be visible
```

**Comment by iarwain** [comment]
Do you have a callstack?

**Comment by iarwain** [comment]
I couldn't reproduce the crash issue, however the slow down is to be expected as you're registering a new event handler every single frame (`orxEvent_AddHandler(orxEVENT_TYPE_RENDER, RenderEventHandler);`).
This means you're handling the event once the first frame, twice the second and so on. When you reached tens of thousands of event handling per frame, each one producing a draw call (`orxDisplay_DrawOBox`), the framerate slows down to a crawl.

You should be calling `orxEvent_AddHandler(orxEVENT_TYPE_RENDER, RenderEventHandler);` only once, in the `Init` function.

Alternatively, I'd suggest using the data-driven approach and simply having your box as an object, which should entirely eliminate all the drawing code from this sample.

**Comment by iarwain** [comment]
(Sorry, didn't mean to close the issue...)

**Comment by OneArb** [comment]
The clang code runs when adding:

```
#include <iostream>
```

**Comment by iarwain** [comment]
@OneArb  Was there another question you'd like answered or can the issue be closed?

**Comment by OneArb** [comment]
1) I never saw a callstack. Left running enough time, the Esc key stops responding and I cannot switch out and back to the application.

2) I can still Ctl-C from the terminal.

I didn't save my compilers flags and project. I am no longer able to reproduce the issue.

clang runs fine without `#include <iostream>` now.

3) I'm trying to build an IDE and create assets at runtime. Isn't the ini file meant for static assets?

**Comment by iarwain** [comment]
@OneArb You can use the config resource at runtime by using the `orxConfig` API, you don't need to set everything offline in .ini files.
Using object might be easier to manage more complex UIs, especially if you want features like grouping.
You can also mix offline and runtime configuration values. For example you can define a base box offline with something like:
```ini
[BoxBase]
Graphic = @
Texture = path/to/texture
Group = UI
...
```
And then at runtime set other properties prior to instantiating them using `orxConfig_Set*()`, prior to creating the object with `orxObject_CreateFromConfig()`.

Both approaches are valid though, the object-oriented one will result in less code and less bookkeeping overall and more controls over transitions, rendering order, etc... but doing direct draw calls is still an option if you prefer (it won't get the benefits of draw call batching optimizations though).

**Comment by OneArb** [comment]
At this point I am trying to figure the scope of what I can do with the orx API and use it as much as I can.

For instance can I draw the sprite / object / texture into the buffer that holds the actual raster?
The idea is to redraw the asset according to the scale and / or zoom factor and also draw assets on the screen at runtime to create new objects.

I looked over CreationTemplate.ini and I see the benefit of using those properties for setup purpose.

Within the context of an IDE, it would make sense to edit the property tree in ImGUI and issue OrxConfig calls to save to file.

**Comment by iarwain** [comment]
I think that discussion should probably be moved to the forum as it might serve other people later and isn't related to the original issue. Would closing this issue and moving the discussion to the forum work for you?

**Comment by OneArb** [comment]
I started [orx IDE thread](https://forum.orx-project.org/discussion/9072/orx-ide/p1)

Thanks
