### ISSUE TITLE
Bad CPU type in executable on mac

### ISSUE THREAD

**Issue by dotmilk** [orx/orx#48]
macOs Catalina 10.15.1
./setup.sh: line 16: code/build/rebol/r3-mac: Bad CPU type in executable

I'm assuming this is due to apple disabling 32bit support in Catalina. Is there a way to rebuild this executable?

**Comment by iarwain** [comment]
Hi @dotmilk,

You're assuming correctly.
I was planning to do it over the past weekend but got sick and didn't find the time to do it.
I'll try to update it in the coming days, however you can indeed compile it yourself in the meantime.

The repository can be found at https://github.com/orx/r3
Instructions are in https://github.com/orx/r3/blob/master/HOWTO.md

I believe you'll need to set `OS_ID` to `0.2.40` for osx-x64.

**Comment by dotmilk** [comment]
https://s3.amazonaws.com/r3bootstraps/r3-osx-x64-8994d23

The specified key does not exist.
r3-osx-x64-8994d23

If i go back up to https://s3.amazonaws.com/r3bootstraps/ there is a

r3-osx-x64-8994d23-debug

however no non debug version as per the linked HowTo

**Comment by iarwain** [comment]
Even though I haven't tried it myself, I think a debug build would work just as well, albeit more slowly.

**Comment by dotmilk** [comment]
Good up until, it tries to use gcc, which on osx is clang and it uses `-static-libgcc` which is not an option for osx's alias. I notice in the make.r there is [this bit](https://github.com/orx/r3/blob/master/make.r#L551)

I don't know enough about rebol to figure it out, but it looks like it is possible for it to use clang somehow?

**Comment by iarwain** [comment]
Ah I see. Unfortunately I'm not well versed in Rebol's internal code nor build process. I've been cross-compiling all the versions from a linux box so far.

But you're right, it seems there might be an option to use clang as well but the people at https://github.com/metaeducation/ren-c are probably much more knowledgeable on that topic than me.

I'll still try to have a look tonight.

**Comment by iarwain** [comment]
I've updated the binary for osx/x64. Could you pull the latest and tell me if it's now working for you?

**Comment by dotmilk** [comment]
Everything works fine now. Got all the way through the [mac guide](https://orx-project.org/wiki/en/orx/mac/setting_up_a_project_on_mac), ran the demo game. 

Thank you!

**Comment by iarwain** [comment]
Perfect, thanks for confirming.

Don't hesitate if you have any questions, either on https://forum.orx-project.org or https://gitter.im/orx/orx
