### ISSUE TITLE
init.bat creates a broken project if $ORX not set

### ISSUE THREAD

**Issue by jasonperry** [orx/orx#50]
`init.bat` should check if the ORX environment variable is set and refuse to create a project. As is, it gives no warning and creates a project with missing references (at least for VS 2019).

To reproduce: build orx, `set ORX=`, `.\init.bat`, generate project with default settings, then open the VS 2019 .sln file. It gives an error "orx.h not found".

**Comment by iarwain** [comment]
`init` doesn't require the environment variable to be set as it is not using it.

The environment variable will be used at build time, which allows you to switch between multiple installations of orx, or even move your installation of orx, while not having to modify the projects created with `init` themselves.

The `ORX` environment variable is set when calling `setup`. If a user is to modify it manually, we expect them to know what they're doing.
Even if `init` were to check the environment variable, you could reproduce the same issue by calling `set ORX=` after running it, you would still not be able to build your project.

**Comment by jasonperry** [comment]
This actually happened to me accidentally, because I didn't start a new command prompt after running `setup.bat`, and so the variable was not set. Anyway, closing because the root cause was user error. Thanks for an awesome framework.

**Comment by iarwain** [comment]
My pleasure, I'm glad you enjoy it.
Don't hesitate to report any other weird behavior you see. If you have questions, there's also always someone around [on the forum](https://forum.orx-project.org) or on the chat (https://gitter.im/orx/orx)
