### ISSUE TITLE
base/orxBuild.h missing 

### ISSUE THREAD

**Issue by IstiCusi** [orx/orx#57]
#include "base/orxBuild.h" of ./orx/code/include/base/orxVersion.h is not existing -- should be checked in or the 
logic modified -- this pops up in the IDEs as missing include. 

Cheers,

Stephan

**Comment by iarwain** [comment]
Hi,

This file is used locally only and is generated when the `setup` script is run.

After cloning the repository, the `setup` script needs to be run once *manually*, cf https://wiki.orx-project.org/en/tutorials/orx/cloning_orx_from_github

It'll then register itself to your SCM of choice (both git and mercurial are currently supported) and run automatically upon subsequent pull/update/checkout.

**Comment by iarwain** [comment]
Hi @IstiCusi, were you able to verify that `orxVersion.h` was correctly created after running `setup`?
