### ISSUE TITLE
Presence of init script

### ISSUE THREAD

**Issue by Zac610** [orx/orx#58]
Insert init.bat/.sh script in dev packages if possible; if not, indicate in the readme in which packages the script is.

**Comment by iarwain** [comment]
Thanks for the suggestion.

Currently the `init` tool is only part of the `src` package.

Given the low frequency of those prebuilt packages releases and the recent efforts that went into having a first time user experience as streamlined as possible using the source repositories, we might simply drop those packages entirely.

Using the `master` branch from a source clone remains the recommended way to use orx.
