### ISSUE TITLE
Missing premake4.exe into code\build\ directory

### ISSUE THREAD

**Issue by Zac610** [orx/orx#59]
The init.bat script stops in calling `code/build/template/../premake4.exe` with error "Unable to find specified file".

Workaround: copy the premake4.exe file from tools\orxCrypt\build\ (or tools\orxFontGen\build\, the are binary the same) to the code\build\ directory.

BTW1: as the premake4 executable is the same, it could be put in a common directory and called from it (for example in tools/), if it can be done.

BTW2: hope my issues help; if not, I can stop bother you :)

**Comment by iarwain** [comment]
Thanks for reporting the issues, every info is always helpful. :)

In this case `premake4.exe` should have been copied when running the `setup` script. According to the other issue you had trouble running `setup` though, and I wonder if you were able to run it after having manually filled the cache with the external ZIP archive you downloaded.

As `setup` should then copy premake, set the environment variables, add the mercurial/git hooks if it's run inside a clone and lastly generate all the project files for the current OS.

Hopefully, cloning the latest repository should address both the issues you encountered in a single pass. :)

**Comment by Zac610** [comment]
I downloaded the latest codebase (as zip) and all worked as a charm.

You were right: both of the problems reported were resolved with the latest version: next time I will be careful to open issues only after getting lates version!

**Comment by iarwain** [comment]
No worries, thank you for taking the time to report the issues in the first place.
