### ISSUE TITLE
download of extern data failed

### ISSUE THREAD

**Issue by Zac610** [orx/orx#60]
The script setup.bat try to download extern data into cache directory; but the download is corrupted(*).

Workaround: get the url of extern data to download (for example `https://codeload.github.com/orx/orx-extern/zip/78cfc9cde31b`) and put it into browser, it will download the data; move the data into cache/ directory, rename it and re-launch setup.bat

(*)I can say it is corrupted as the size is lower when downloaded by setup.bat script, and the zip will not open. All is fine if the zip is downloaded by browser.

**Comment by iarwain** [comment]
Hi,

Which version of orx are you using? The latest from a source clone?
This has been addressed two weeks ago and should work for everyone.

**Comment by Zac610** [comment]
Issue not present in latest commits
