### ISSUE TITLE
Setup script creates .bash_profile if it doesn't exist

### ISSUE THREAD

**Issue by nculwell** [orx/orx#67]
The setup script creates a .bash_profile file in your user directory if .bash_profile doesn't already exist. This can cause a lot of problems, because by default bash runs .profile on logon, but only if no .bash_profile exists. The result is that running the Orx setup script breaks your logon scripts if you rely on .profile.

It looks like the code for this is in code/build/rebol/setup.r. If it were a shell script then I'd say you should just check if the file exists before appending to it. This is a REBOL script, though, and I don't know REBOL so I don't know what you'd do about it.

**Comment by iarwain** [comment]
Thanks for the recommendation, I'll make some changes accordingly in the coming days.
Would you mind testing it once ready? I only have a couple of linux VMs (it's not my default development platform) and none of them use bash by default.

**Comment by iarwain** [comment]
Actually, if you don't mind doing a quick test, looking at `code/build/rebol/setup.r`, line 148, you should see:

```
      env-home/.bash_profile                rejoin ["export " env-variable "="]   true
```

Replacing `true` to `false` should fix your issue there.

**Comment by iarwain** [comment]
Fix attempt in 25b68300fa2c666f24e087a4ff10591d65988544

**Comment by nculwell** [comment]
Thanks for the response! I tried it and it looks like it worked. I verified that it still appends to .profile (if I remove the setting it puts it back when I run setup.sh) but it doesn't create .bash_profile anymore. Then if I create an empty .bash_profile, it does add the setting there.

**Comment by iarwain** [comment]
Thank you for testing and confirming the fix work!
