### ISSUE TITLE
setup.sh can't download the extern archive

### ISSUE THREAD

**Issue by LittleWhite-tb** [orx/orx#70]
Hello,

On my machine (Linux Manjaro), it appears that the _setup.sh_ can't download the extern archive.
If I follow the link, my Firefox can download it without any problem. `wget` and `curl` can also download it.
Here the output:
```
== Checking version: [ extern/ ]
== [ 56dc8f8b459d ] needed, current [ none ]
== [ 56dc8f8b459d ] not in cache
== Fetching [ https://orx-project.org/extern/56dc8f8b459d.zip ] 
== Please wait!
== Not found!
== Fetching [ https://codeload.github.com/orx/orx-extern/zip/56dc8f8b459d ] 
== Please wait!
== Not found!
== [ 56dc8f8b459d ] not found, aborting!
```
I wonder what the `setup.r` uses for downloading. Can you tell me how to debug it, in order to find what is the source of the problem.

**Comment by iarwain** [comment]
Hi,

Thanks for reporting the issue, @LittleWhite-tb.
I have not seen this issue happening before, however I feel we should be able to get more details without too much hassle, as there should be ways to increase the verbosity of the network exchanges.
I'll just have to do a little investigation on my end beforehand, as it's not something with which I'm very familiar in Rebol 3.

As a side note, HTTP/HTTPS schemes are implemented natively over TCP inside Rebol 3, they do not use any external dependencies as far as I know.

That being said, in order to not get stuck because of the setup process, I'd recommend downloading the archive manually and saving it inside a `cache/` subfolder that you might need to create yourself (ie. at the same level as `code/`).
You can then re-run setup and it should pick it from there, using the manually cached version to finish the process.

**Comment by iarwain** [comment]
So apparently running the script from inside the Rebol 3 console will trigger the first level of verbosity. To do so, simply goes to orx's root folder and start the Rebol 3 console with:
```
./code/build/rebol/r3-linux64
```
(If you're on a 32bit linux, simply remove the trailing 64.)
Then inside the Rebol 3 console, run the following commands:
```
echo %setup.log
do %code/build/rebol/setup.r
```
You should be able to re-read the log when it's over with `more setup.log`.
Alternatively, you can ask for more verbosity by running this command before inside the Rebol 3 console, before running the `do` one:
```
system/options/log/http: 5
```
This should request the highest degree of verbosity for all HTTP/S-based network transactions.

**Comment by LittleWhite-tb** [comment]
Well surprisingly, this time it did work:
```
/code/build/rebol/r3-linux64 ././code/build/rebol/setup.r 
== Checking version: [ extern/ ]
== [ 56dc8f8b459d ] needed, current [ none ]
== [ 56dc8f8b459d ] not in cache
== Fetching [ https://orx-project.org/extern/56dc8f8b459d.zip ] 
== Please wait!
== Not found!
== Fetching [ https://codeload.github.com/orx/orx-extern/zip/56dc8f8b459d ] 
== Please wait!
== [ 56dc8f8b459d ] cached!
== Decompressing [ cache/56dc8f8b459d.zip ] => [ extern/ ]
== [ 56dc8f8b459d ] installed!
== Copying [ premake4 ] to [ code/build ]
== Copying [ premake4 ] to [ tutorial/build ]
== Copying [ premake4 ] to [ tools/orxFontGen/build ]
== Copying [ premake4 ] to [ tools/orxCrypt/build ]
== Setting environment: [ ORX = /home/alexandre/Dev/tests/orx/orx/code ]
== Generating build files for [ linux ]
== Generating [ gmake ]
== Generating [ codelite ]
== Generating [ codeblocks ]
== You can now build orx in [ code/build/linux ]
== For more details, please refer to [ https://orx-project.org/wiki/ ]
== Installing git hook [ post-checkout ]
== Installing git hook [ post-merge ]


== IMPORTANT - Make sure the following libraries (or equivalent) are installed on your system:
==[ libgl1-mesa-dev ]
==[ libxrandr-dev ]

== IMPORTANT - New environment detected: Please logout/login to refresh your environment if you're using an IDE. 

== [ 0:00:19 ] Setup successful!
```

So, I did retry from "scratch":
```
rm -r ./extern/ ./cache/
```

Retry with the shell script:
```
./setup.sh 
== Checking version: [ extern/ ]
== [ 56dc8f8b459d ] needed, current [ none ]
== [ 56dc8f8b459d ] not in cache
== Fetching [ https://orx-project.org/extern/56dc8f8b459d.zip ] 
== Please wait!
== Not found!
== Fetching [ https://codeload.github.com/orx/orx-extern/zip/56dc8f8b459d ] 
== Please wait!
== Not found!
== [ 56dc8f8b459d ] not found, aborting!
```

But this one works:
```
./code/build/rebol/r3-linux64 -qs ././code/build/rebol/setup.r
```
In the Rebol console:
```
>> do %code/build/rebol/setup.r
 [REBOL] Script: "Setup" Version: 0.0.0 Date: 26-Sep-2015
== Checking version: [ extern/ ]
== [ 56dc8f8b459d ] needed, current [ none ]
== [ 56dc8f8b459d ] not in cache
== Fetching [ https://orx-project.org/extern/56dc8f8b459d.zip ] 
== Please wait!
 [HTTP] Opening connection: tls://orx-project.org:443
 [HTTP] Request: {GET /extern/56dc8f8b459d.zip HTTP/1.1^M
Accept: */*^M
Accept-charset: utf-8^M
Accept-Encoding: gzip,deflate^M
Host: orx-project.org^M
User-Agent: REBOL^M
}
 [HTTP] Headers: [
    Content-Length: none
    Content-Encoding: "gzip"
    Transfer-Encoding: "chunked"
    Last-Modified: none
    Date: "Sat, 02 Apr 2022 14:18:21 GMT"
    Content-Type: "text/html"
    Connection: "keep-alive"
    Cache-Control: {private, no-cache, no-store, must-revalidate, max-age=0}
    pragma: "no-cache"
    vary: "User-Agent, Accept-Encoding"
    alt-svc: {h3=":443"; ma=86400, h3-29=":443"; ma=86400}
    x-turbo-charged-by: "LiteSpeed"
    CF-Cache-Status: "BYPASS"
    Expect-CT: {max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"}
    Report-To: {{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=yZoAGtWmDZqYILVJnpiCEXJ8r923N8dZAlkjfM4JsDTuPb39j%2Fe5SkHCFwYqOpXCg8uEvX8anhDnAwDaP8zRpNPUwo1plRsE7aMdPBXz%2F2ZS9MLheelj8BryA8CDP642Ce8%3D"}],"group":"cf-nel","max_age":604800}}
    NEL: {{"success_fraction":0,"report_to":"cf-nel","max_age":604800}}
    Server: "cloudflare"
    CF-RAY: "6f5a317ad8db975e-AMS"
]
== Not found!
== Fetching [ https://codeload.github.com/orx/orx-extern/zip/56dc8f8b459d ] 
== Please wait!
 [HTTP] Opening connection: tls://codeload.github.com:443
 [HTTP] Request: {GET /orx/orx-extern/zip/56dc8f8b459d HTTP/1.1^M
Accept: */*^M
Accept-charset: utf-8^M
Accept-Encoding: gzip,deflate^M
Host: codeload.github.com^M
User-Agent: REBOL^M
}
 [HTTP] Headers: [
    Content-Length: "56618596"
    Content-Encoding: none
    Transfer-Encoding: none
    Last-Modified: none
    Access-Control-Allow-Origin: "https://render.githubusercontent.com"
    content-disposition: "attachment; filename=orx-extern-56dc8f8b459d.zip"
    Content-Security-Policy: {default-src 'none'; style-src 'unsafe-inline'; sandbox}
    Content-Type: "application/zip"
    ETag: {W/"787734837a33d58c044cd69dea19f12fd7ea269266de843d7a04dde607a1c9f3"}
    Strict-Transport-Security: "max-age=31536000"
    Vary: "Authorization,Accept-Encoding,Origin"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "deny"
    X-XSS-Protection: "1; mode=block"
    Date: "Sat, 02 Apr 2022 14:18:22 GMT"
    X-GitHub-Request-Id: "FADA:09C7:A101F:DA38E:62485B2D"
]
 [HTTP] Done reading: 56618596 bytes
== [ 56dc8f8b459d ] cached!
== Decompressing [ cache/56dc8f8b459d.zip ] => [ extern/ ]
 [ZIP] Decode ZIP data ( 56618596 bytes )
```

(Please not, the first link (on orx-project.org) give me a 404 in the browser.)

Also note that once I got it working with rebol (with options `-qs`), it does also work by calling the shell script (of course, I delete the extern and cache folder). But if I do a new git clone of ORX, the shell script will again fail (I would suppose rebol does have an additional cache).

And now, it does work everytime... so, no luck.

**Comment by iarwain** [comment]
Thanks for the time & energy you've put in testing this.
Unfortunately we haven't learned much so far. If you ever stumble upon the issue again with the debug logs active, please let me know.

In the meantime, I'll add a `debug` option to the script to easily turn verbosity on and make it easier to troubleshoot in the future.

**Comment by iarwain** [comment]
Support for a `-d`/`-debug` argument has been added to the setup script in c0d147526fda4b4233d451cb284494c844d94fe3:
Running `./setup.sh -debug` will trigger the first level of verbosity for debugging whereas `./setup.sh -debug:5` will trigger the maximum verbosity level.

**Comment by hcarty** [comment]
Thanks for adding the debug option! As I think I've mentioned in Discord before, I've run into this 404 issie in the OCaml bindings CI a few times. Now that the debug option is available I can use it if I start seeing the behavior again.

**Comment by LittleWhite-tb** [comment]
I have retried two times today and I am unable to reproduce it. Nevertheless the debug option is a good idea.
I think we can close this ticket. It could be anything (like ISP, routing, DNS...)

**Comment by iarwain** [comment]
Thanks for testing again in any case.
Don't hesitate to re-open the ticket if the problem comes back.

**Comment by AlexandruSimandi** [comment]
I have the same exact problem in windows and wsl. Maybe there is a missing dependency or something?

**Comment by iarwain** [comment]
@AlexandruSimandi Thanks for reporting the issue.
I'll see what I can do to have multiple mirrors to host those dependency archives, which should hopefully alleviate that problem.
