### ISSUE TITLE
About the topic of cross-compilation from Linux.

### ISSUE THREAD

**Issue by MetalMaxMX** [orx/orx#83]
Hi! I just wanted to ask, rather quickly. If the Orx game engine supported cross-compiling from one host to another? I haven't seen anything in the documentation that implies or hints that it can do so (nor on the website) so I am wondering if this is possible. When I mean cross-compiling in this scenario, I am talking about things like compiling from Linux to Windows and maybe viceversa? (I do know that you can set up mingw on Linux so I was wondering if this kind of setup was officially supported or so)

**Comment by iarwain** [comment]
Hi @MetalMaxMX.

In the past, some people have been cross-compiling orx.
If my memory serves me well, they were compiling all versions from a Linux box.

As far as I know, there shouldn't be any issue doing cross-compiling, as orx is a very straightforward C  program in the end, and all dependencies are available in binary form for all the target platforms.

That being said, I've never tried to cross-compile it myself (beside Linux32 vs Linux64).

If you want to give it a try and run into any issues, please feel free to poke us on our Discord server.

**Comment by MetalMaxMX** [comment]
Hey @iarwain Thanks for answering my query! 

If there is history and knowledge of people already cross-compiling Orx onto other platforms, that's good enough for me! This is a topic that appears rather rarely among game engines and frameworks so seeing confirmation of sorts with this gives me a bit of confidence with this codebase. As you have stated, I may hop onto your Discord if I ever run into such an scenario, but again, happy that it has a high likelihood of success.

**Comment by iarwain** [comment]
My pleasure!

I'm confident you should be able to succeed without too much hassle.

In any case, feel free to join us on Discord and ask any questions you have, not just the cross-compiling ones.
Discord's also the place where we gather all learning materials and discuss community-driven projects/endeavors.

**Comment by MetalMaxMX** [comment]
All right! Sounds once again rather good. Since my questions on cross-compiling may go for a little bit on this issue, feel free to close it since confirmation was, again, good enough for my test-cases. (and the fact that you believe it is possible without much hassle is also good and gives me even more confidence) 

Just tell me if it's also fair to post on the forums? I've noticed they are not very active but I would also like for other people to view it on something a bit more searchable on a regular search engine? Even if to post questions or solutions in them.

**Comment by iarwain** [comment]
Yes, the forum is a good place too.
You will definitely have less eyeballs there though.
With Discord supporting advanced searches and threads, most people just stick with Discord nowadays, but the forum is still valid.
